
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
environment: testing
enabled: true
server:
  port: 8888
#logging:
#  level:
#    root: INFO
compas:
  scl:
    schema:
      paths:
        scl: "classpath:xsd/SCL2007B4/SCL.xsd"

#Metrics related configurations
management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: "*"
      #base-path: "/"
  endpoint:
    metrics:
      enabled: true
      prometheus:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
host: jaxb-perf-metrics-dev
service: jaxb-perf
region: Europe/Paris
