spring:

server:
  port: 8888
#  connection-timeout: -1
#  tomcat:
#    connectionUploadTimeout: 1800000
#    connectionTimeout: 1800000
#    connection-timeout: 1800000
#    max-swallow-size: 100000000
#    max-http-form-post-size: 100000000
  level:
    root: INFO
compas:
  scl:
    schema:
      paths:
        scl: "classpath:xsd/SCL2007B4/SCL.xsd"