apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: Prometheus
  type: prometheus
  access: direct
  orgId: 1
  url: http://localhost:9090
  basicAuth: false
  withCredentials: false
  isDefault: true
  version: 1
  editable: true