global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 30s
  external_labels:
    monitor: 'my-project'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    # dns_sd_configs:
    # - names:
    #   - 'app'
    #   type: 'A'
    #   port: 8082
    static_configs:
      - targets: ['app:8080']